config/routes.rb
Rails.application.routes.draw do
  resources :products do
    resources :variants
  end
  resources :news
    devise_for :users
  
  resources :users

  get 'login/index' 
  get "up" => "rails/health#show", as: :rails_health_check
  root "welcome#index"
end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # Defines the root path route ("/")

app/models/address.rb
class Address < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
end

app/models/cart_line.rb
class CartLine < ApplicationRecord
  belongs_to :variant
end

app/models/news.rb
class News < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_one :shipping_address,class_name: "Address"
  has_one :billing_address,class_name: "Address"
end

app/models/order_line.rb
class OrderLine < ApplicationRecord
  belongs_to :variant
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :variants
end

app/models/user.rb
class User < ApplicationRecord
end

app/models/variant.rb
class Variant < ApplicationRecord
  belongs_to :product
  monetize :price_cents
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
    def index
    end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: %i[ show edit update destroy ]

  # GET /news or /news.json
  def index
    @news = News.all
  end

  # GET /news/1 or /news/1.json
  def show
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news or /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to news_url(@news), notice: "News was successfully created." }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1 or /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to news_url(@news), notice: "News was successfully updated." }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1 or /news/1.json
  def destroy
    @news.destroy!

    respond_to do |format|
      format.html { redirect_to news_index_url, notice: "News was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def news_params
      params.require(:news).permit(:title, :author, :content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/signin_helper.rb
module SigninHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/variant_helper.rb
module VariantHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/news/_form.html.erb
<%= form_with(model: news) do |form| %>
  <% if news.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
        <% news.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :author, style: "display: block" %>
    <%= form.text_field :author %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/news/_news.html.erb
<div id="<%= dom_id news %>">
  <p>
    <strong>Title:</strong>
    <%= news.title %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= news.author %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= news.content %>
  </p>

</div>

app/views/news/edit.html.erb
<h1>Editing news</h1>

<%= render "form", news: @news %>

<br>

<div>
  <%= link_to "Show this news", @news %> |
  <%= link_to "Back to news", news_index_path %>
</div>

app/views/news/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>News</h1>

<div id="news">
  <% @news.each do |news| %>
    <%= render news %>
    <p>
      <%= link_to "Show this news", news %>
    </p>
  <% end %>
</div>

<%= link_to "New news", new_news_path %>

app/views/news/new.html.erb
<h1>New news</h1>

<%= render "form", news: @news %>

<br>

<div>
  <%= link_to "Back to news", news_index_path %>
</div>

app/views/news/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @news %>

<div>
  <%= link_to "Edit this news", edit_news_path(@news) %> |
  <%= link_to "Back to news", news_index_path %>

  <%= button_to "Destroy this news", @news, method: :delete %>
</div>