config/routes.rb
Rails.application.routes.draw do
  resources :products do
    resources :variants
  end
  resources :news
    devise_for :users
  
  resources :users

  get 'login/index' 
  get "up" => "rails/health#show", as: :rails_health_check
  root "welcome#index"
end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # Defines the root path route ("/")

app/models/address.rb
class Address < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
end

app/models/cart_line.rb
class CartLine < ApplicationRecord
  belongs_to :variant
end

app/models/news.rb
class News < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_one :shipping_address,class_name: "Address"
  has_one :billing_address,class_name: "Address"
end

app/models/order_line.rb
class OrderLine < ApplicationRecord
  belongs_to :variant
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :variants
end

app/models/user.rb
class User < ApplicationRecord
end

app/models/variant.rb
class Variant < ApplicationRecord
  belongs_to :product
  monetize :price_cents
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
    def index
    end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: %i[ show edit update destroy ]

  # GET /news or /news.json
  def index
    @news = News.all
  end

  # GET /news/1 or /news/1.json
  def show
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news or /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to news_url(@news), notice: "News was successfully created." }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1 or /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to news_url(@news), notice: "News was successfully updated." }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1 or /news/1.json
  def destroy
    @news.destroy!

    respond_to do |format|
      format.html { redirect_to news_index_url, notice: "News was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def news_params
      params.require(:news).permit(:title, :author, :content)
    end
end

app/controllers/variants_controller.rb
class VariantsController < ApplicationController
  before_action :set_product
  before_action :set_variant, only: %i[ show edit update destroy ]


# GET products/variants or products/variants.json
def index
  @variants = @product.variants.all
end

# GET products/variants/1 or products/variants/1.json
def show
end

# GET products/variants/new
def new
  @variant = @product.variants.new
end

# GET products/variants/1/edit
def edit
end


# POST products/variants or products/variants.json
def create
  @variant = @product.variants.new(variant_params)

  if @variant.save
    redirect_to product_variants_url(@product,@variant), notice: "Variant was successfully created." 
  else
    render :new, status: :unprocessable_entity
  end
end

# PATCH/PUT products/variants/1 or products/variants/1.json
def update
    if @variant.update(variant_params)
      redirect_to product_variants_url(@variant), notice: "Variant was successfully updated." 
    else
      render :edit, status: :unprocessable_entity 
    end
end

# DELETE products/variants/1 or products/variants/1.json
def destroy
  @variant.destroy

  respond_to do |format|
    format.html { redirect_to product_variants_url(@product), notice: "Variant was successfully destroyed." }
    format.json { head :no_content }
  end
end

private
  # Use callbacks to share common setup or constraints between actions.

  def set_product
    @product = Product.find(params[:product_id])
  end

  def set_variant
    @variant = @product.variants.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def variant_params
    params.require(:variant).permit(:sku, :price_cents)
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/signin_helper.rb
module SigninHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/variant_helper.rb
module VariantHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/variants/_form.html.erb
<%= form_with(model: [@product, variant]) do |form| %>
    <% if variant.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(variant.errors.count, "error") %> prohibited this variant from being saved:</h2>
  
        <ul>
          <% variant.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div>
      <%= form.label :sku, style: "display: block" %>
      <%= form.text_field :sku %>
    </div>
  
    <div>
      <%= form.label :price_cents, style: "display: block" %>
      <%= form.text_field :price_cents %>
    </div>
  
    <div>
      <%= form.submit %>
    </div>
  <% end %>

app/views/variants/edit.html.erb
<h1>Editing variant</h1>

<%= render "form", variant: @variant %>

<br>

<div>
  <%= link_to "Back to variants", variants_path %>
</div>

app/views/variants/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Variants for <%=@product.name%></h1>

<div id="variants">

  <table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Sku</th>
            <th>Price</th>
        </tr>
    </thead>
    <tbody>
    <% @variants.each do |variant| %>
        <tr id="<%= dom_id variant %>">
           <td><%= variant.id %></td> 
           <td><%= variant.sku %></td> 
           <td><%= variant.price %></td>
        </tr>
      <% end %>
    </tbody>
  </table> 

</div>

<%= link_to "New variant", new_product_variant_path(product: @product) %>

app/views/variants/new.html.erb
<h1>New variant</h1>

<%= render "form", variant: @variant %>

<br>

<div>
  <%= link_to "Back to variants", product_variants_path(@product) %>
</div>

app/views/variants/price_cents:integer.html.erb
<h1>Variant#price_cents:integer</h1>
<p>Find me in app/views/variant/price_cents:integer.html.erb</p>

app/views/variants/product:references.html.erb
<h1>Variant#product:references</h1>
<p>Find me in app/views/variant/product:references.html.erb</p>

app/views/variants/sku.html.erb
<h1>Variant#sku</h1>
<p>Find me in app/views/variant/sku.html.erb</p>